# ---- 全域設定 ----
seed: 0
device: "cuda:0"

log_save_tb: false
log_frequency: 10000

# Environment
env: "unity_env"
executable_path: None
decision_interval: 1
render: true

# Replay buffer & training schedule
replay_buffer_capacity: 1000000
num_train_steps: 1000000
num_seed_steps: 5000
eval_frequency: 5000
num_eval_episodes: 5

# ---- Agent 設定（對應 SACAgent 參數）----
agent:
  name: "sac"  
  # obs_dim / action_dim / action_range / device 會在程式裡自動填
  discount: 0.99
  init_temperature: 0.1

  alpha_lr: 1e-4
  alpha_betas: [0.9, 0.999]

  actor_lr: 1e-4
  actor_betas: [0.9, 0.999]
  actor_update_frequency: 1

  critic_lr: 1e-4
  critic_betas: [0.9, 0.999]
  critic_tau: 0.005
  critic_target_update_frequency: 2

  batch_size: 1024
  learnable_temperature: true

  critic_cfg:
    hidden_dim: 1024
    hidden_depth: 2

  actor_cfg:
    hidden_dim: 1024
    hidden_depth: 2
    log_std_bounds: [-5, 2]
